### ISSUE TITLE
Incompatible OPB property error hidden by search dialog

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#31]
To reproduce bug: Add OPB:Chemical concentration at the start of a blank composite annotation, then hit the "Add entity" button. Then go back and search for a new OPB term to replace Chemical concentration. Search for "flow rate" and select "Chemical molar flow rate." The error message indicating that the OPB property is not valid for a physical entity is hidden by the search dialog.

Also, when you click OK on the error message, the search dialog should stay open rather than close.

**Comment by thompsct** [comment]
Fixed the second issue and I think I fixed the first issue (the dialog gets minimized in Windows when the error message appears).

**Comment by maxneal** [comment]
I confirmed that the second issue is fixed, but the first issue persists.

**Comment by thompsct** [comment]
Try it now.

**Comment by maxneal** [comment]
Nope…first issue persists.  I get a null pointer error if I expose the error message window and close it:

**Comment by thompsct** [comment]
I re-targeted the error dialog to use the selector dialog as its parent. This should resolve the issue.

**Comment by maxneal** [comment]
Fixed! Thank you.
